# Generated by Django 5.2.7 on 2025-10-23 02:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('duration', models.DurationField()),
                ('distance', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('sport_category', models.CharField(choices=[('running', 'Running'), ('cycling', 'Cycling'), ('swimming', 'Swimming')], default='running', max_length=20)),
                ('calories_burned', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('done_at', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
