# Generated by Django 5.2.6 on 2025-10-24 16:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseactivity',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='place.place'),
        ),
        migrations.AlterField(
            model_name='exerciseactivity',
            name='calories_burned',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='exerciseactivity',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
