# Generated by Django 5.2.7 on 2025-10-24 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_exerciseactivity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseactivity',
            name='calories_burned',
            field=models.PositiveBigIntegerField(),
        ),
    ]
