# Generated by Django 5.2.7 on 2025-10-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_alter_exerciseactivity_calories_burned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseactivity',
            name='calories_burned',
            field=models.FloatField(blank=True),
        ),
    ]
