# Generated by Django 5.2.7 on 2025-10-24 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_exerciseactivity_calories_burned'),
        ('place', '0004_place_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseactivity',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='place.place'),
        ),
    ]
