# Generated by Django 5.2.5 on 2025-10-15 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
