# Generated by Django 5.2.6 on 2025-10-16 04:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
