# Generated by Django 5.2.6 on 2025-10-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_forumpost_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
