# Generated by Django 5.2.6 on 2025-10-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_forumpost_last_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='last_edited',
            field=models.DateTimeField(default=None),
        ),
    ]
