# Generated by Django 5.2.6 on 2025-10-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_alter_forumpost_last_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='last_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
