# Generated by Django 5.2.6 on 2025-10-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_forumpost_likes_forumreply_quote_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='product_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
