# Generated by Django 5.2.5 on 2025-12-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
