# Generated by Django 5.2.5 on 2025-10-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_place_admin_place_created_at_place_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='genre',
            field=models.CharField(blank=True, choices=[('Swimming Pool', 'Swimming Pool'), ('Running Track', 'Running Track'), ('Bicycle Tracking', 'Bicycle Tracking')], default=None, max_length=100, null=True),
        ),
    ]
