# Generated by Django 5.2.5 on 2025-10-23 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='products',
            new_name='product',
        ),
    ]
