# Generated by Django 5.2.6 on 2025-10-24 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_remove_userprofile_bio'),
        ('user_profile', '0003_userprofile_first_name_userprofile_last_name'),
    ]

    operations = [
    ]
