# Generated by Django 5.2.5 on 2025-10-26 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_merge_20251024_1633'),
        ('user_profile', '0004_merge_20251024_1652'),
    ]

    operations = [
    ]
