# Generated by Django 5.2.6 on 2025-10-24 13:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_place_genre'),
        ('ticket', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['id'], 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='place_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='place_name',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='price_per_ticket',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='visit_date',
        ),
        migrations.AddField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='customer_name',
            field=models.CharField(default='Unknown', max_length=200, verbose_name='Customer Name'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='place.place', verbose_name='Sport Place'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Ticket Quantity'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='booking_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Booking Date'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_tickets', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
